# Generated by Django 5.0.1 on 2024-02-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='DAPR',
            new_name='AWND',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='MDPR',
            new_name='TAVG',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='SNWD',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='TOBS',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='WT01',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='WT03',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='WT04',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='WT05',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='WT06',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='WT11',
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='NAME',
            field=models.CharField(max_length=200),
        ),
    ]
