# Generated by Django 4.2.10 on 2024-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldmap', '0002_rename_dapr_weatherdata_awnd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalData',
            fields=[
                ('fips_code', models.IntegerField(blank=True, null=True)),
                ('station_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('Elevation', models.FloatField(blank=True, null=True)),
                ('Month', models.CharField(max_length=255)),
                ('PRCP', models.FloatField(blank=True, null=True)),
                ('AWND', models.FloatField(blank=True, null=True)),
                ('TAVG', models.FloatField(blank=True, null=True)),
                ('TMAX', models.FloatField(blank=True, null=True)),
                ('TMIN', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'worldmap_GlobalData',
            },
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
