# Generated by Django 4.2.11 on 2024-05-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldmap', '0003_globaldata_delete_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaldata',
            name='date_recorded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
